In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle


from Models.Augment import Augment

/Users/theoevans/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/theoevans/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/theoevans/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/theoevans/anaconda3/envs/cv/lib/python3

In [25]:
THIS_DIR = os.path.abspath('')
DATASETS_DIR = "Datasets/"
dataset_npz = "cells_64x64_it_50.npz"

dataset_npz_filepath = os.path.join(THIS_DIR, DATASETS_DIR, dataset_csv)
data = np.load(dataset_npz_filepath, allow_pickle = True)
    
features = data["features"]
target = data["target"]

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.33, random_state=42)
print(np.append(X_test[0], features[0], axis= 0))


[[[[0.9254902  0.9254902  0.93333334]
   [0.9254902  0.9254902  0.93333334]
   [0.92941177 0.92941177 0.92941177]
   ...
   [0.9019608  0.8784314  0.9254902 ]
   [0.9411765  0.91764706 0.95686275]
   [0.94509804 0.92156863 0.9607843 ]]

  [[0.9372549  0.91764706 0.90588236]
   [0.94509804 0.9254902  0.9137255 ]
   [0.9490196  0.93333334 0.92156863]
   ...
   [0.88235295 0.8666667  0.92156863]
   [0.93333334 0.92156863 0.9647059 ]
   [0.9411765  0.92941177 0.95686275]]

  [[0.95686275 0.9137255  0.8901961 ]
   [0.9647059  0.92941177 0.9019608 ]
   [0.972549   0.94509804 0.92156863]
   ...
   [0.8666667  0.85882354 0.9137255 ]
   [0.92156863 0.91764706 0.9490196 ]
   [0.9411765  0.9372549  0.95686275]]

  ...

  [[0.92941177 0.9137255  0.96862745]
   [0.9137255  0.9019608  0.94509804]
   [0.9098039  0.90588236 0.9372549 ]
   ...
   [0.77254903 0.627451   0.5254902 ]
   [0.8627451  0.72156864 0.63529414]
   [0.9647059  0.84313726 0.77254903]]

  [[0.87058824 0.8627451  0.9137255 ]
   [0.8

In [15]:
def create_train_and_test_files(npz_filepath, test_size = 0.33, augment = True, transformations = ['rotate', 'flip']):
    
    data = np.load(npz_filepath, allow_pickle = True)
    
    features = data["features"]
    target = data["target"]
        
    X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = test_size, random_state=42)
    
    print("Without augmentation:")
    print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
    
    if augment:
        aug = Augment()
        for i in range(0, len(X_train)):
            image_to_transform = X_train[i]
            target = y_train[i]
            transformed_images = aug.TransformImage(image_to_transform, transformations)
            
            for transformed_image in transformed_images:
                X_train = np.append(X_train, transformed_image, axis = 0)
                y_train = np.append(y_train, target, axis = 0)

        X_train, y_train = shuffle(X_train, y_train)
        
        print("With augmentation:")
        print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
        
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = create_train_and_test_files(dataset_npz_filepath)


Without augmentation:
(2542,) (2542,) (1253,) (1253,)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 3 dimension(s)

In [52]:
X_train.shape

(2542,)

In [20]:
def load_data(dataset_name):
    this_dir = os.path.abspath('')
    datasets_dir = os.path.join(this_dir, DATASETS_DIR)

    return np.load(f"{datasets_dir}{dataset_name}.npz", allow_pickle=True)

In [21]:
data = load_data(dataset_name)

In [23]:
data['y_train']

array(['non_tumor', 'non_tumor', 'non_tumor', ..., 'tumor', 'non_tumor',
       'tumor'], dtype=object)

In [17]:
def generate_tf_training_files(dataset_name, batch_size = 512, shuffle = True):

    train_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x": train_test_data['X_train']},
        y=train_test_data['y_train'],
        num_epochs=None,
        shuffle=True)
        
estimator = generate_tf_training_files(dataset_name)

In [18]:
estimator